version: "3"
networks:
 client:
  driver: bridge

services:
  client:
     container_name: daemon-client
     image: sumitanand17/test:v1
     ports:
       - "3000:3000"
     restart: unless-stopped
     depends_on:
       - mongo
     networks:
      - client

  mongo:
     container_name: mongo
     image: mongo:4.0.4
     volumes:
       - "mongo:/data/db"
       - "mongo:/data/configdb"
     ports:
       - "27017:27017"
     restart: unless-stopped
     networks:
       - client
volumes:
   mongo:
